### PR TITLE
Added missing Entity.setAbility(this) where i could as FavouriteDragon asked me

### PR DESCRIPTION
**Pull request by handicraftsman**

### CODE REVIEW

**Comment by handicraftsman** [comment]
Ok wat?

```
:sonarqubeSonarQube server [http://localhost:9000] can not be reached
```

That's definitely not my problem.

**Comment by FavouriteDragon** [comment]
Looks good!

**Comment by FavouriteDragon** [comment]
ok hopefully this doesn't break everything!

**Comment by FavouriteDragon** [comment]
well it worked for me
i think

**Pull request merged**
