### PR TITLE
Fd/old packets

### PR DESCRIPTION
**Pull request by Aang23**
Well, this PR only updated the mappings to stable_39, which are those recommended in 1.12.x. Not much, but helps quite a lot when you're used to those.
Sorry for the unnecessary "Fixed the build" commit, blame Amuzil's maven repo for that !

### CODE REVIEW

**Comment by FavouriteDragon** [comment]
Looks good to me!

**Comment by FavouriteDragon** [comment]
@Mahtaran Can you check this as well? This should be good, but make sure I haven't missed anything.

**Comment by Aang23** [comment]
If you're wondering why Travis failed : 
`SonarQube server [http://localhost:9000] can not be reached`

**Comment by Mahtaran** [comment]
Oh well, this sucks. I have just finished updating everything to the correct mappings myself. I will see if I missed anything that you have in your commits.

**Comment by Aang23** [comment]
Ok, I just looked at your commit and everything looks good.

**Comment by Mahtaran** [comment]
Yep, looks like everything is the same. No need to merge then.

**Comment by Mahtaran** [comment]
Also if you were wondering Amuzil is just the "company" I use to host all of my things, such as a Git server, a Maven server, a way to have a custom email domain and a domain to host my websites and game servers.

**Comment by Mahtaran** [comment]
So no need to blame Amuzil's Maven repo, blame my rusty server computer and Archiva for shitting on me. 😜

**Comment by Aang23** [comment]
Ok ! Thanks for the info.

**Pull request closed without merging**
